name: CI

on:
  pull_request:
  pull_request_target:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: ./scripts/echo-foo.sh
        env:
          FOO: ${{ secrets.FOO }}
