name: CI

on:
  pull_request:
  pull_request_target:
    types: [labeled]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' || (github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'safe to test'))  }}

    steps:
      - uses: actions/checkout@v3
      - run: ./scripts/echo-foo.sh
        env:
          FOO: ${{ secrets.FOO }}
