name: CI

on:
  pull_request:
  pull_request_target:
  pull_request_review:
    types: [submitted]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: ./scripts/echo-foo.sh
        env:
          FOO: ${{ secrets.FOO }}

  approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "This PR was approved"
      - run: ./scripts/echo-foo.sh
        env:
          FOO: ${{ secrets.FOO }}