name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_target:
    types: [opened, synchronize, reopened, labeled]
  push:
    branches:
      - main

jobs:
  can-run-ci:
    runs-on: ubuntu-latest
    if: |
      (!github.event.pull_request.head.repo.fork) ||
      (github.event.pull_request.head.repo.fork)
    steps:
      - name: ok
        run: echo "yes"

  test:
    runs-on: ubuntu-latest
    needs: [can-run-ci]
    if: ${{ github.event_name == 'pull_request' || (github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'safe to test'))  }}

    steps:
      - uses: actions/checkout@v3
      - name: run script
        run: ./scripts/echo-foo.sh
        env:
          FOO: ${{ secrets.FOO }}

      - name: dump context
        run: echo '${{ toJSON(github) }}'
